# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

Qi.out.dir/home/nugunga/Desktop/interpreter/Qi.cpp.o: /home/nugunga/Desktop/interpreter/Qi.cpp
Qi.out.dir/home/nugunga/Desktop/interpreter/Qi.cpp.o: /home/nugunga/Desktop/interpreter/Qi.h
Qi.out.dir/home/nugunga/Desktop/interpreter/Qi.cpp.o: /home/nugunga/Desktop/interpreter/Qi_prot.h

Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_code.cpp.o: /home/nugunga/Desktop/interpreter/Qi.h
Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_code.cpp.o: /home/nugunga/Desktop/interpreter/Qi_code.cpp
Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_code.cpp.o: /home/nugunga/Desktop/interpreter/Qi_prot.h

Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_misc.cpp.o: /home/nugunga/Desktop/interpreter/Qi.h
Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_misc.cpp.o: /home/nugunga/Desktop/interpreter/Qi_misc.cpp
Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_misc.cpp.o: /home/nugunga/Desktop/interpreter/Qi_prot.h

Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_pars.cpp.o: /home/nugunga/Desktop/interpreter/Qi.h
Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_pars.cpp.o: /home/nugunga/Desktop/interpreter/Qi_pars.cpp
Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_pars.cpp.o: /home/nugunga/Desktop/interpreter/Qi_prot.h

Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_tbl.cpp.o: /home/nugunga/Desktop/interpreter/Qi.h
Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_tbl.cpp.o: /home/nugunga/Desktop/interpreter/Qi_prot.h
Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_tbl.cpp.o: /home/nugunga/Desktop/interpreter/Qi_tbl.cpp

Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_tkn.cpp.o: /home/nugunga/Desktop/interpreter/Qi.h
Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_tkn.cpp.o: /home/nugunga/Desktop/interpreter/Qi_prot.h
Qi.out.dir/home/nugunga/Desktop/interpreter/Qi_tkn.cpp.o: /home/nugunga/Desktop/interpreter/Qi_tkn.cpp

