# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/nugunga/Documents/git repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/CMake/CMake_Sub/polish"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/nugunga/Documents/git repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/CMake/CMake_Sub/polish"

# Include any dependencies generated for this target.
include CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/flags.make

CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/home/nugunga/Documents/git_repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c.o: CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/flags.make
CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/home/nugunga/Documents/git_repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c.o: /home/nugunga/Documents/git\ repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/nugunga/Documents/git repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/CMake/CMake_Sub/polish/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/home/nugunga/Documents/git_repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c.o"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/home/nugunga/Documents/git_repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c.o   -c "/home/nugunga/Documents/git repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c"

CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/home/nugunga/Documents/git_repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/home/nugunga/Documents/git_repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c.i"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E "/home/nugunga/Documents/git repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c" > CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/home/nugunga/Documents/git_repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c.i

CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/home/nugunga/Documents/git_repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/home/nugunga/Documents/git_repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c.s"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S "/home/nugunga/Documents/git repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c" -o CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/home/nugunga/Documents/git_repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c.s

# Object files for target ../../../Source/Test/polish/polishtest.out
__/__/__/Source/Test/polish/polishtest_out_OBJECTS = \
"CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/home/nugunga/Documents/git_repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c.o"

# External object files for target ../../../Source/Test/polish/polishtest.out
__/__/__/Source/Test/polish/polishtest_out_EXTERNAL_OBJECTS =

../../../Source/Test/polish/polishtest.out: CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/home/nugunga/Documents/git_repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c.o
../../../Source/Test/polish/polishtest.out: CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/build.make
../../../Source/Test/polish/polishtest.out: CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir="/home/nugunga/Documents/git repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/CMake/CMake_Sub/polish/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_2) "Linking C executable ../../../Source/Test/polish/polishtest.out"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/build: ../../../Source/Test/polish/polishtest.out

.PHONY : CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/build

CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/cmake_clean.cmake
.PHONY : CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/clean

CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/depend:
	cd "/home/nugunga/Documents/git repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/CMake/CMake_Sub/polish" && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" "/home/nugunga/Documents/git repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/CMake/CMake_Sub/polish" "/home/nugunga/Documents/git repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/CMake/CMake_Sub/polish" "/home/nugunga/Documents/git repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/CMake/CMake_Sub/polish" "/home/nugunga/Documents/git repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/CMake/CMake_Sub/polish" "/home/nugunga/Documents/git repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/CMake/Source/Test/polish/polishtest.out.dir/DependInfo.cmake" --color=$(COLOR)
.PHONY : CMakeFiles/../../../Source/Test/polish/polishtest.out.dir/depend

