# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

/home/nugunga/Documents/git\ repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/CMake/Source/Test/polish/polishtest.out.dir/home/nugunga/Documents/git_repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c.o: /home/nugunga/Documents/git\ repos/QuantumCompilerInterpreter/QuantumCompilerInterPreter_Main/Source/Test/polish/PolishTest.c

