# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi.cpp
Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi.h
Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_prot.h

Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_code.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi.h
Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_code.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_code.cpp
Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_code.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_prot.h

Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_misc.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi.h
Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_misc.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_misc.cpp
Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_misc.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_prot.h

Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_pars.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi.h
Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_pars.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_pars.cpp
Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_pars.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_prot.h

Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_tbl.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi.h
Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_tbl.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_prot.h
Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_tbl.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_tbl.cpp

Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_tkn.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi.h
Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_tkn.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_prot.h
Excute/Qi.out.dir/home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_tkn.cpp.o: /home/nugunga/Desktop/git/QuantumCompilerInterpreterTest/interpreter/Qi_tkn.cpp

